## Lets define some variables. ##

variables:
  url:
    required: true
    default: https://petstore3.swagger.io/api/v3/openapi.json
    
## NOTHING BELOW SHOULD BE MODIFIED ##

name: gh-actions-swagger-to-postman
author: antyung88
description: Convert Swagger URL To Postman Collection

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    # Install Node on the runner
    - name: Install Node
      uses: actions/setup-node@v3
      with:
        node-version: "14.x"
    - name: Install openapi-to-postmanv2
      run: |
        npm i -g openapi-to-postmanv2
        sudo mkdir -p ./postman
        sudo wget ${{ inputs.url }} -O ./postman/swagger.json && sudo chown -R 1001:1001 ./postman
        openapi2postmanv2 -s ./postman/swagger.json -o ./postman/collection.json
      shell: bash
    - uses: actions/upload-artifact@v3
      with:
        path: ./postman/*
      
