## Lets define some variables. ##

inputs:
  url:
    required: true
    default: https://petstore3.swagger.io/api/v3/openapi.json
    
## NOTHING BELOW SHOULD BE MODIFIED ##

name: gh-actions-swagger-to-postman
author: antyung88
description: Convert Swagger URL To Postman Collection

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - name: Install openapi-to-postmanv2
      run: |
        sudo mkdir -p ./postman
        sudo wget ${{ inputs.url }} -O ./postman/swagger.json && sudo chown -R 1001:1001 ./postman
        docker run -v $(pwd)/postman:/postman ghcr.io/antyung88/openapi2postmanv2:latest openapi2postmanv2 -s /postman/swagger.json -o /postman/collection.json
      shell: bash
    - uses: actions/upload-artifact@v3
      with:
        path: ./postman/*
      
