## Lets define some variables. ##

variables:
  url:
    required: true
    default: https://petstore3.swagger.io/api/v3/openapi.json
  artifact:
    default: false
    
## NOTHING BELOW SHOULD BE MODIFIED ##

name: gh-actions-swagger-to-postman
author: antyung88
description: Convert Swagger URL To Postman Collection

runs:
  using: composite
  steps:
    - uses: actions/checkout@v2
    # Install Node on the runner
    - name: Install Node
      uses: actions/setup-node@v3
      with:
        node-version: "14.x"
    - name: Install newman & openapi-to-postmanv2 & run
      run: |
        npm install -g newman
        npm i -g openapi-to-postmanv2
        sudo mkdir -p ./newman
        sudo wget ${{ inputs.url }} -O ./newman/swagger.json && sudo chown -R 1001:1001 ./newman
        openapi2postmanv2 -s ./newman/swagger.json -o ./newman/collection.json && sudo chown -R 1001:1001 ./newman
        newman run ./newman/collection.json
      shell: bash
    - uses: actions/upload-artifact@v3
      if: ${{ github.event.inputs.artifact == 'true' }}
      with:
        path: ./newman/*
