name: Create Actions Release

on:
  push:
  workflow_dispatch:
    inputs:
      job:
        description: 'Job to run.'
        required: true
        default: 'deploy'

jobs:

  deploy-build:
    name: Deploy Release
    if: ${{ github.event.inputs.job == 'deploy'}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: v2.1
          release_name: v2.1
          draft: false

  build-stable:
    name: Build Stable Image
    if: ${{ github.event.inputs.job == 'docker'}}
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v3
      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}
      - run: |
          docker build . -t ghcr.io/${{ github.actor }}/${{ secrets.image }}:latest
          docker push ghcr.io/${{ github.actor }}/${{ secrets.image }}:latest

