name: Create Actions Release

on:
  push:
  workflow_dispatch:
    inputs:
      job:
        description: 'Job to run.'
        required: true
        default: 'deploy'

jobs:

  test-build:
    name: Convert Swagger URL to Postman
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v3
      - uses: antyung88/gh-actions-swagger-to-postman@v1.8
        with:
          url: https://petstore3.swagger.io/api/v3/openapi.json
      - run: |
          cat ./postman/swagger.json
          cat ./postman/collection.json

  deploy-build:
    name: Deploy Release
    if: ${{ github.event.inputs.job == 'deploy'}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: "v1.8"
          release_name: "v1.8"
          draft: false
          pre-release: true
