name: Test Release

on:
  push:
  pull_request:

jobs:

  test-build:
    name: Test Convert Swagger URL to Postman
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v3
      - uses: antyung88/gh-actions-swagger-to-postman@v1.9
        with:
          url: https://petstore3.swagger.io/api/v3/openapi.json
      - run: |
          cat ./postman/swagger.json
          cat ./postman/collection.json
